server:
    port:8081
spring:
  application:
    name: spring-boot-jwt
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: spring-boot-jwt/src/main/java
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.41:3306/test
    username: root
    password: root123


#jwt token
jwt:
  name: Huang
  base64Secret: 7786df7fc3a34e26a61c034d5ec8245d
  jwtExpires: 120

mybatis:
  type-aliases-package: com.jwt.entity
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

